name: neolatino_dictionario
description: Dictionario Neolatino
label: Dictionario Neolatino

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  csv: ^5.0.0-nullsafety.0
  bloc: ^7.0.0-nullsafety.3
  flutter_bloc: ^7.0.0-nullsafety.4
  flutter_spinkit: ^5.0.0
  google_fonts: ^2.0.0
  diacritic: ^0.1.1
  url_launcher: ^6.0.2
  font_awesome_flutter: ^9.0.0-nullsafety
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/neolatino.png
    - assets/fonts/
    - assets/dict/
    - assets/icons/
