name: neolatino_dictionario
description: Dictionario Neolatino
label: Dictionario Neolatino

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0'

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.0
  collection: ^1.16.0
  csv: ^5.0.1
  diacritic: ^0.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  font_awesome_flutter: ^10.2.1
  go_router: ^5.1.0
  google_fonts: ^3.0.1
  http: ^0.13.5
  loading_animation_widget: ^1.2.0+3
  oxidized: ^5.2.0
  provider: ^6.0.4
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
